package gipsy.tests.junit.GEE.multitier.DST.ws;
import static org.junit.Assert.*;

import org.junit.Test;
import gipsy.GEE.multitier.DST.ws.test.src.test.WSDSTWrapperServiceLocator;
import junit.framework.TestCase;

/**
 * The class <code>WSDSTWrapperServiceLocatorTest</code> contains tests for the
 * class {@link <code>WSDSTWrapperServiceLocator</code>}
 *
 * @pattern JUnit Test Case
 *
 * @generatedBy CodePro at 25/3/16 6:07 PM
 *
 * @author Deepaak
 *
 * @version $Revision$
 */
public class WSDSTWrapperServiceLocatorTest extends TestCase {

	/**
	 * Construct new test instance
	 *
	 * @param name the test name
	 */
	public WSDSTWrapperServiceLocatorTest(String name) {
		super(name);
	}

	/**
	 * Run the java.lang.String getWSDSTWrapperAddress() method test
	 */
	@Test
	public void testGetWSDSTWrapperAddress() {
		fail("Not yet implemented");
		
	}

	/**
	 * Run the java.lang.String getWSDSTWrapperWSDDServiceName() method test
	 */
	@Test
	public void testGetWSDSTWrapperWSDDServiceName() {
		fail("Not yet implemented");
		
	}

	/**
	 * Run the void setWSDSTWrapperWSDDServiceName(java.lang.String) method
	 * test
	 */
	@Test
	public void testSetWSDSTWrapperWSDDServiceName() {
		fail("Not yet implemented");
		
	}

	/**
	 * Run the test.WSDSTWrapper getWSDSTWrapper() method test
	 */
	@Test
	public void testGetWSDSTWrapper() {
		fail("Not yet implemented");
		
	}

	/**
	 * Run the void setWSDSTWrapperEndpointAddress(java.lang.String) method
	 * test
	 */
	@Test
	public void testSetWSDSTWrapperEndpointAddress() {
		fail("Not yet implemented");
	
	}

	/**
	 * Run the java.rmi.Remote getPort(Class) method test
	 */
	@Test
	public void testGetPort() {
		fail("Not yet implemented");
	
	}

	/**
	 * Run the javax.xml.namespace.QName getServiceName() method test
	 */
	@Test
	public void testGetServiceName() {
		fail("Not yet implemented");
		
	}

	/**
	 * Run the java.util.Iterator getPorts() method test
	 */
	@Test
	public void testGetPorts() {
		fail("Not yet implemented");
	
	}

	/**
	 * Run the void setEndpointAddress(java.lang.String, java.lang.String)
	 * method test
	 */
	@Test
	public void testSetEndpointAddress() {
		fail("Not yet implemented");
		
	}
}

/*$CPS$ This comment was generated by CodePro. Do not edit it.
 * patternId = com.instantiations.assist.eclipse.pattern.testCasePattern
 * strategyId = com.instantiations.assist.eclipse.pattern.testCasePattern.junitTestCase
 * additionalTestNames = 
 * assertTrue = false
 * callTestMethod = true
 * createMain = false
 * createSetUp = false
 * createTearDown = false
 * createTestFixture = false
 * createTestStubs = true
 * methods = 
 * package = gipsy.tests.junit.GEE.multitier.DST.ws
 * package.sourceFolder = GIPSY/src
 * superclassType = junit.framework.TestCase
 * testCase = WSDSTWrapperServiceLocatorTest
 * testClassType = gipsy.GEE.multitier.DST.ws.test.src.test.WSDSTWrapperServiceLocator
 */