package gipsy.tests.junit.GEE.multitier.DST.ws;
import static org.junit.Assert.*;

import org.junit.Test;

import gipsy.GEE.multitier.DST.ws.test.src.test.WSDSTWrapperSoapBindingStub;
import junit.framework.TestCase;

/**
 * The class <code>WSDSTWrapperSoapBindingStubTest</code> contains tests for
 * the class {@link <code>WSDSTWrapperSoapBindingStub</code>}
 *
 * @pattern JUnit Test Case
 *
 * @generatedBy CodePro at 25/3/16 6:09 PM
 *
 * @author Deepaak
 *
 * @version $Revision$
 */
public class WSDSTWrapperSoapBindingStubTest extends TestCase {

	/**
	 * Construct new test instance
	 *
	 * @param name the test name
	 */
	public WSDSTWrapperSoapBindingStubTest(String name) {
		super(name);
	}

	/**
	 * Run the test.WSDemand getHashTableValue(test.WSDemandSignature) method
	 * test
	 */
	@Test
	public void testGetHashTableValue() {
		fail("Not yet implemented");
		
	}

	/**
	 * Run the test.WSDemandSignature setHashTable(test.WSDemand) method test
	 */
	@Test
	public void testSetHashTable() {
		fail("Not yet implemented");
		
	}

	/**
	 * Run the test.WSDemand getPendingDemand() method test
	 */
	@Test
	public void testGetPendingDemand() {
		fail("Not yet implemented");
		
	}
}

/*$CPS$ This comment was generated by CodePro. Do not edit it.
 * patternId = com.instantiations.assist.eclipse.pattern.testCasePattern
 * strategyId = com.instantiations.assist.eclipse.pattern.testCasePattern.junitTestCase
 * additionalTestNames = 
 * assertTrue = false
 * callTestMethod = true
 * createMain = false
 * createSetUp = false
 * createTearDown = false
 * createTestFixture = false
 * createTestStubs = true
 * methods = 
 * package = gipsy.tests.junit.GEE.multitier.DST.ws
 * package.sourceFolder = GIPSY/src
 * superclassType = junit.framework.TestCase
 * testCase = WSDSTWrapperSoapBindingStubTest
 * testClassType = gipsy.GEE.multitier.DST.ws.test.src.test.WSDSTWrapperSoapBindingStub
 */