# Main Documentaiton Makefile
#
# $Header: /cvsroot/gipsy/gipsy/doc/Makefile,v 1.2 2003/09/04 20:49:57 mokhov Exp $
#

all clean maintainer-clean:
	@echo "Docs makefile (and docs themselves) are yet to be added."

# EOF
