# General Debuggers Makefile
# Serguei Mokhov
#
# $Header: /cvsroot/gipsy/gipsy/src/gipsy/RIPE/debugger/Makefile,v 1.2 2005/09/04 18:41:04 mokhov Exp $
#

all clean maintainer-clean:
	@echo "There is not very much to do in the debuggers directory yet."

# EOF
