/* Generated By:JJTree: Do not edit this line. DFGParserTreeConstants.java */

package gipsy.GIPC.DFG.DFGAnalyzer;

public interface DFGParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTDIGRAPH = 2;
  public int JJTGRAPH = 3;
  public int JJTNODE = 4;
  public int JJTEDGE = 5;
  public int JJTASSIGN = 6;
  public int JJTSUB = 7;
  public int JJTDIR = 8;
  public int JJTID = 9;


  public String[] jjtNodeName = {
    "Start",
    "void",
    "DIGRAPH",
    "GRAPH",
    "NODE",
    "EDGE",
    "ASSIGN",
    "SUB",
    "DIR",
    "ID",
  };
}
