/* Generated By:JJTree&JavaCC: Do not edit this line. DFGParserConstants.java */
package gipsy.GIPC.DFG.DFGAnalyzer;

public interface DFGParserConstants {

  int EOF = 0;
  int ASSIGN = 7;
  int GT = 8;
  int LT = 9;
  int EQ = 10;
  int LE = 11;
  int GE = 12;
  int NE = 13;
  int OR = 14;
  int AND = 15;
  int NOT = 16;
  int PLUS = 17;
  int MINUS = 18;
  int STAR = 19;
  int SLASH = 20;
  int REM = 21;
  int ASA = 22;
  int FBY = 23;
  int UPON = 24;
  int WVR = 25;
  int FIRST = 26;
  int NEXT = 27;
  int PREV = 28;
  int ISEOD = 29;
  int AT = 30;
  int WHEN = 31;
  int DIGRAPH = 32;
  int GRAPH = 33;
  int NODE = 34;
  int EDGE = 35;
  int SUBGRAPH = 36;
  int LINK = 37;
  int IDENTIFIER = 38;
  int LETTER = 39;
  int DIGIT = 40;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"or\"",
    "\"and\"",
    "\"not\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"asa\"",
    "\"fby\"",
    "\"upon\"",
    "\"wvr\"",
    "\"first\"",
    "\"next\"",
    "\"prev\"",
    "\"iseod\"",
    "\"@\"",
    "\"#\"",
    "\"digraph\"",
    "\"graph\"",
    "\"node\"",
    "\"edge\"",
    "\"subgraph\"",
    "\"->\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\"\\\"\"",
  };

}
