/* Generated By:JJTree: Do not edit this line. ObjectiveIndexicalLucidParserTreeConstants.java */

package gipsy.GIPC.intensional.SIPL.ObjectiveLucid;

public interface ObjectiveIndexicalLucidParserTreeConstants
{
  public int JJTVOID = 0;
  public int JJTSTART = 1;
  public int JJTIF = 2;
  public int JJTHASH = 3;
  public int JJTPOSI = 4;
  public int JJTNEGE = 5;
  public int JJTADD = 6;
  public int JJTMIN = 7;
  public int JJTOR = 8;
  public int JJTLT = 9;
  public int JJTGT = 10;
  public int JJTGE = 11;
  public int JJTLE = 12;
  public int JJTEQ = 13;
  public int JJTNE = 14;
  public int JJTAT = 15;
  public int JJTWHERE = 16;
  public int JJTQLIST = 17;
  public int JJTFBY = 18;
  public int JJTDIM = 19;
  public int JJTWVR = 20;
  public int JJTASA = 21;
  public int JJTUPON = 22;
  public int JJTOBJREF = 23;
  public int JJTPARAS = 24;
  public int JJTFUN = 25;
  public int JJTTIMES = 26;
  public int JJTDIV = 27;
  public int JJTMOD = 28;
  public int JJTAND = 29;
  public int JJTNOT = 30;
  public int JJTFIRST = 31;
  public int JJTNEXT = 32;
  public int JJTPREV = 33;
  public int JJTISEOD = 34;
  public int JJTDIMENSION = 35;
  public int JJTASSIGN = 36;
  public int JJTID = 37;
  public int JJTCONST = 38;
  public int JJTEMBED = 39;
  public int JJTARRAY = 40;
  public int JJTURL = 41;


  public String[] jjtNodeName = {
    "void",
    "START",
    "IF",
    "HASH",
    "POSI",
    "NEGE",
    "ADD",
    "MIN",
    "OR",
    "LT",
    "GT",
    "GE",
    "LE",
    "EQ",
    "NE",
    "AT",
    "WHERE",
    "Qlist",
    "FBY",
    "DIM",
    "WVR",
    "ASA",
    "UPON",
    "OBJREF",
    "PARAS",
    "FUN",
    "TIMES",
    "DIV",
    "MOD",
    "AND",
    "NOT",
    "FIRST",
    "NEXT",
    "PREV",
    "ISEOD",
    "DIMENSION",
    "ASSIGN",
    "ID",
    "CONST",
    "EMBED",
    "ARRAY",
    "URL",
  };
}
