/* Generated By:JJTree&JavaCC: Do not edit this line. ObjectiveIndexicalLucidParserConstants.java */
package gipsy.GIPC.intensional.SIPL.ObjectiveLucid;

public interface ObjectiveIndexicalLucidParserConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 6;
  int FORMAL_COMMENT = 7;
  int MULTI_LINE_COMMENT = 8;
  int DIMENSION = 9;
  int ELSE = 10;
  int END = 11;
  int FI = 12;
  int IF = 13;
  int THEN = 14;
  int WHERE = 15;
  int EMBED = 16;
  int ASSIGN = 17;
  int GT = 18;
  int LT = 19;
  int EQ = 20;
  int LE = 21;
  int GE = 22;
  int NE = 23;
  int OR = 24;
  int AND = 25;
  int NOT = 26;
  int BITAND = 27;
  int BITOR = 28;
  int PLUS = 29;
  int MINUS = 30;
  int STAR = 31;
  int SLASH = 32;
  int REM = 33;
  int ASA = 34;
  int FBY = 35;
  int UPON = 36;
  int WVR = 37;
  int FIRST = 38;
  int NEXT = 39;
  int PREV = 40;
  int ISEOD = 41;
  int AT = 42;
  int WHEN = 43;
  int INTEGER_LITERAL = 44;
  int DECIMAL_LITERAL = 45;
  int HEX_LITERAL = 46;
  int OCTAL_LITERAL = 47;
  int FLOATING_POINT_LITERAL = 48;
  int EXPONENT = 49;
  int CHARACTER_LITERAL = 50;
  int STRING_LITERAL = 51;
  int ID = 52;
  int LETTER = 53;
  int DIGIT = 54;
  int LPAREN = 55;
  int RPAREN = 56;
  int LBRACKET = 57;
  int RBRACKET = 58;
  int SEMICOLON = 59;
  int COMMA = 60;
  int DOT = 61;
  int ILLEGALCHAR = 62;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<SINGLE_LINE_COMMENT>",
    "<FORMAL_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "\"dimension\"",
    "\"else\"",
    "\"end\"",
    "\"fi\"",
    "\"if\"",
    "\"then\"",
    "\"where\"",
    "\"embed\"",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"or\"",
    "\"and\"",
    "\"not\"",
    "\"&\"",
    "\"|\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"asa\"",
    "\"fby\"",
    "\"upon\"",
    "\"wvr\"",
    "\"first\"",
    "\"next\"",
    "\"prev\"",
    "\"iseod\"",
    "\"@\"",
    "\"#\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "<ID>",
    "<LETTER>",
    "<DIGIT>",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "<ILLEGALCHAR>",
  };

}
