/* Generated By:JJTree&JavaCC: Do not edit this line. JGIPLParserConstants.java */
package gipsy.GIPC.intensional.SIPL.JLucid;

public interface JGIPLParserConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 6;
  int FORMAL_COMMENT = 7;
  int MULTI_LINE_COMMENT = 8;
  int DIMENSION = 9;
  int ELSE = 10;
  int END = 11;
  int FI = 12;
  int IF = 13;
  int THEN = 14;
  int WHERE = 15;
  int EMBED = 16;
  int ASSIGN = 17;
  int GT = 18;
  int LT = 19;
  int EQ = 20;
  int LE = 21;
  int GE = 22;
  int NE = 23;
  int BITOR = 24;
  int BITAND = 25;
  int OR = 26;
  int AND = 27;
  int NOT = 28;
  int PLUS = 29;
  int MINUS = 30;
  int TIMES = 31;
  int DIV = 32;
  int MOD = 33;
  int DOT = 34;
  int AT = 35;
  int HASH = 36;
  int CONST = 37;
  int INTEGER_LITERAL = 38;
  int DECIMAL_LITERAL = 39;
  int HEX_LITERAL = 40;
  int OCTAL_LITERAL = 41;
  int FLOATING_POINT_LITERAL = 42;
  int EXPONENT = 43;
  int CHARACTER_LITERAL = 44;
  int STRING_LITERAL = 45;
  int ID = 46;
  int LETTER = 47;
  int DIGIT = 48;
  int LPAREN = 49;
  int RPAREN = 50;
  int LBRACKET = 51;
  int RBRACKET = 52;
  int SEMICOLON = 53;
  int COMMA = 54;
  int ILLEGALCHAR = 55;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<SINGLE_LINE_COMMENT>",
    "<FORMAL_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "\"dimension\"",
    "\"else\"",
    "\"end\"",
    "\"fi\"",
    "\"if\"",
    "\"then\"",
    "\"where\"",
    "\"embed\"",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"|\"",
    "\"&\"",
    "\"or\"",
    "\"and\"",
    "\"not\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\".\"",
    "\"@\"",
    "\"#\"",
    "<CONST>",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "<ID>",
    "<LETTER>",
    "<DIGIT>",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "<ILLEGALCHAR>",
  };

}
