# Tools Makefile to build under UNIXen
#
# $Header: /cvsroot/gipsy/gipsy/src/tools/Makefile,v 1.1 2003/09/02 00:10:00 mokhov Exp $

all clean:
	@echo "Requires fixing and filling in with some real build stuff..."

maintainer-clean: clean

# EOF
