/* Generated By:JJTree: Do not edit this line. .\LucxParserTreeConstants.java */

package gipsy.GIPC.intensional.SIPL.Lucx;

public interface LucxParserTreeConstants
{
  public int JJTVOID = 0;
  public int JJTSTART = 1;
  public int JJTASSIGN = 2;
  public int JJTIF = 3;
  public int JJTHASH = 4;
  public int JJTPOSI = 5;
  public int JJTNEGE = 6;
  public int JJTADD = 7;
  public int JJTMIN = 8;
  public int JJTOR = 9;
  public int JJTLT = 10;
  public int JJTGT = 11;
  public int JJTGE = 12;
  public int JJTLE = 13;
  public int JJTEQ = 14;
  public int JJTNE = 15;
  public int JJTAT = 16;
  public int JJTWHERE = 17;
  public int JJTQLIST = 18;
  public int JJTFBY = 19;
  public int JJTWVR = 20;
  public int JJTASA = 21;
  public int JJTUPON = 22;
  public int JJTDIM = 23;
  public int JJTPARAS = 24;
  public int JJTFUN = 25;
  public int JJTTIMES = 26;
  public int JJTDIV = 27;
  public int JJTMOD = 28;
  public int JJTAND = 29;
  public int JJTEXTRACT = 30;
  public int JJTOVERRIDE = 31;
  public int JJTPROJECT = 32;
  public int JJTHIDE = 33;
  public int JJTDIFFERENTIATE = 34;
  public int JJTSUBSTITUTE = 35;
  public int JJTINTERSECT = 36;
  public int JJTUNION = 37;
  public int JJTCHOOSE = 38;
  public int JJTISSUBCONTEXT = 39;
  public int JJTISSUPCONTEXT = 40;
  public int JJTRANGE = 41;
  public int JJTDIRECTEDRANGE = 42;
  public int JJTCOMPARESET = 43;
  public int JJTJOIN = 44;
  public int JJTNOT = 45;
  public int JJTUNIOP = 46;
  public int JJTNEXT = 47;
  public int JJTPREV = 48;
  public int JJTISEOD = 49;
  public int JJTISEMPTY = 50;
  public int JJTISSET = 51;
  public int JJTISBOX = 52;
  public int JJTSIMPLECONTEXT = 53;
  public int JJTCONTEXTSET = 54;
  public int JJTCONTEXT_ELEMENT = 55;
  public int JJTDIMENSION = 56;
  public int JJTORDEREDINFINITENONPERIODICTAGSET_INFINITE = 57;
  public int JJTPERIOD = 58;
  public int JJTORDEREDFINITEPERIODICTAGSET = 59;
  public int JJTORDEREDFINITENONPERIODICTAGSET_ENUMERATED = 60;
  public int JJTLOWER = 61;
  public int JJTUPPER = 62;
  public int JJTORDEREDFINITENONPERIODICTAGSET_LOWERUPPER = 63;
  public int JJTSTEP = 64;
  public int JJTORDEREDFINITENONPERIODICTAGSET_LOWERUPPERSTEP = 65;
  public int JJTORDEREDINFINITEPERIODICTAGSET = 66;
  public int JJTORDEREDINFINITENONPERIODICTAGSET_LOWER = 67;
  public int JJTORDEREDINFINITENONPERIODICTAGSET_LOWERSTEP = 68;
  public int JJTORDEREDINFINITENONPERIODICTAGSET_UPPER = 69;
  public int JJTORDEREDINFINITENONPERIODICTAGSET_UPPERSTEP = 70;
  public int JJTUNORDEREDFINITEPERIODICTAGSET = 71;
  public int JJTUNORDEREDFINITENONPERIODICTAGSET = 72;
  public int JJTUNORDEREDINFINITEPERIODICTAGSET = 73;
  public int JJTID = 74;
  public int JJTINTEGER = 75;
  public int JJTFLOAT = 76;
  public int JJTSTRING = 77;


  public String[] jjtNodeName = {
    "void",
    "START",
    "ASSIGN",
    "IF",
    "HASH",
    "POSI",
    "NEGE",
    "ADD",
    "MIN",
    "OR",
    "LT",
    "GT",
    "GE",
    "LE",
    "EQ",
    "NE",
    "AT",
    "WHERE",
    "Qlist",
    "FBY",
    "WVR",
    "ASA",
    "UPON",
    "DIM",
    "PARAS",
    "FUN",
    "TIMES",
    "DIV",
    "MOD",
    "AND",
    "EXTRACT",
    "OVERRIDE",
    "PROJECT",
    "HIDE",
    "DIFFERENTIATE",
    "SUBSTITUTE",
    "INTERSECT",
    "UNION",
    "CHOOSE",
    "ISSUBCONTEXT",
    "ISSUPCONTEXT",
    "RANGE",
    "DIRECTEDRANGE",
    "COMPARESET",
    "JOIN",
    "NOT",
    "uniOp",
    "NEXT",
    "PREV",
    "ISEOD",
    "ISEMPTY",
    "ISSET",
    "ISBOX",
    "SIMPLECONTEXT",
    "CONTEXTSET",
    "CONTEXT_ELEMENT",
    "DIMENSION",
    "ORDEREDINFINITENONPERIODICTAGSET_INFINITE",
    "PERIOD",
    "ORDEREDFINITEPERIODICTAGSET",
    "ORDEREDFINITENONPERIODICTAGSET_ENUMERATED",
    "LOWER",
    "UPPER",
    "ORDEREDFINITENONPERIODICTAGSET_LOWERUPPER",
    "STEP",
    "ORDEREDFINITENONPERIODICTAGSET_LOWERUPPERSTEP",
    "ORDEREDINFINITEPERIODICTAGSET",
    "ORDEREDINFINITENONPERIODICTAGSET_LOWER",
    "ORDEREDINFINITENONPERIODICTAGSET_LOWERSTEP",
    "ORDEREDINFINITENONPERIODICTAGSET_UPPER",
    "ORDEREDINFINITENONPERIODICTAGSET_UPPERSTEP",
    "UNORDEREDFINITEPERIODICTAGSET",
    "UNORDEREDFINITENONPERIODICTAGSET",
    "UNORDEREDINFINITEPERIODICTAGSET",
    "ID",
    "INTEGER",
    "FLOAT",
    "STRING",
  };
}
