/* Generated By:JJTree&JavaCC: Do not edit this line. PreprocessorParserConstants.java */
package gipsy.GIPC.Preprocessing;

public interface PreprocessorParserConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 6;
  int FORMAL_COMMENT = 7;
  int MULTI_LINE_COMMENT = 8;
  int LPAREN = 9;
  int RPAREN = 10;
  int COLON = 11;
  int SEMICOLON = 12;
  int COMMA = 13;
  int DOUBLE_QUOTE = 14;
  int SINGLE_QUOTE = 15;
  int TYPEDECL = 16;
  int FUNCDECL = 17;
  int IPLDECL = 18;
  int IMMUTABLE = 19;
  int INT = 20;
  int DOUBLE = 21;
  int BOOLEAN = 22;
  int FLOAT = 23;
  int CHAR = 24;
  int STRING = 25;
  int VOID = 26;
  int CHARACTER_LITERAL = 27;
  int STRING_LITERAL = 28;
  int ID = 29;
  int LETTER = 30;
  int DIGIT = 31;
  int LANGID = 32;
  int HASH = 33;
  int CAPITAL_LETTER = 34;
  int LANGDATA = 35;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<SINGLE_LINE_COMMENT>",
    "<FORMAL_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "\"(\"",
    "\")\"",
    "\":\"",
    "\";\"",
    "\",\"",
    "\"\\\"\"",
    "\"\\\'\"",
    "\"#typedecl\"",
    "\"#funcdecl\"",
    "\"#ipldecl\"",
    "\"immutable\"",
    "\"int\"",
    "\"double\"",
    "\"bool\"",
    "\"float\"",
    "\"char\"",
    "\"string\"",
    "\"void\"",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "<ID>",
    "<LETTER>",
    "<DIGIT>",
    "<LANGID>",
    "\"#\"",
    "<CAPITAL_LETTER>",
    "<LANGDATA>",
  };

}
