/**
 * 
 */
package gipsy.GEE.multitier.GMT.demands;

import java.util.UUID;

import gipsy.Configuration;
import gipsy.GEE.IDP.DMSException;
import gipsy.GEE.IDP.demands.DemandSignature;
import gipsy.GEE.IDP.demands.SystemDemand;

/**
 * The system demand sent between GIPSY Node and GMT to report and handle 
 * TA error.
 * 
 * @author Yi Ji
 * @version $Id: DSTIssueReport.java,v 1.1 2011/01/04 19:47:46 ji_yi Exp $
 */
public class DSTIssueReport 
extends SystemDemand 
{
	/**
	 * Generated by Eclipse
	 */
	private static final long serialVersionUID = 2065228472581475584L;
	// To be completed by GIPSY Node
	private Configuration oProblematicTAConfig = null;
	private Configuration oCorrectedTAConfig = null;
	private String strSourceNodeID = null;
	
	private DMSException oTAException = null;
	
	public DSTIssueReport(String pstrSourceNodeID, 
			String pstrDestinationTierID, 
			Configuration poProblematicTAConfig,
			DMSException poTAException)
	{
		this.oSignature = new DemandSignature(UUID.randomUUID().toString());
		this.oDestinationTierID = pstrDestinationTierID;
		this.oProblematicTAConfig = poProblematicTAConfig;
		this.strSourceNodeID = pstrSourceNodeID;
		this.oTAException = poTAException;
	}

	public String getSourceTierID()
	{
		return this.strSourceNodeID;
	}
	
	public void setCorrectedTAConfig(Configuration poCorrectedTAConfig)
	{
		this.oCorrectedTAConfig = poCorrectedTAConfig;
	}
	
	public Configuration getCorrectedTAConfig()
	{
		return this.oCorrectedTAConfig;
	}
	
	public Configuration getProblematicTAConfig()
	{
		return this.oProblematicTAConfig;
	}
	
	public DMSException getTAException()
	{
		return this.oTAException;
	}
}
