package gipsy.GEE.multitier.GMT.demands;

import gipsy.GEE.IDP.demands.SystemDemand;
import gipsy.GEE.multitier.MultiTierException;

public class TierAllocationResult 
extends SystemDemand 
{
	/**
	 * Generated by Eclipse
	 */
	private static final long serialVersionUID = -8746481798680511655L;
	
	private TierRegistration[] aoRegistrations;
	private MultiTierException oException;
	
	
	/**
	 * @param poRegistration
	 * @param poException
	 */
	public TierAllocationResult(TierRegistration[] paoRegistrations,
			MultiTierException poException) 
	{
		super();
		this.aoRegistrations = paoRegistrations;
		this.oException = poException;
	}
	
	public TierRegistration[] getRegistrations() 
	{
		return aoRegistrations;
	}
	public void setRegistrations(TierRegistration[] paoRegistrations) 
	{
		this.aoRegistrations = paoRegistrations;
	}
	public MultiTierException getException() 
	{
		return oException;
	}
	public void setException(MultiTierException poException) 
	{
		this.oException = poException;
	}
	
}
